{
 "title": "Darkstat",
 "tags": [
  "darkstat",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(darkstat_network_receive_bytes_total, host)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  { "title": "Total In (By Host Selection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total In (Time Range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_receive_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total In (Time Range)"
    }
   ]
  },
  {
   "title": "Total In (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_receive_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total In (Today)"
    }
   ]
  },
  {
   "title": "Total In (This Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_receive_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total In (This Week)"
    }
   ]
  },
  {
   "title": "Total In (This Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_receive_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total In (This Month)"
    }
   ]
  },
  {
   "title": "Total In (This Year)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_receive_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total In (This Year)"
    }
   ]
  },
  { "title": "Total Out (By Host Selection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Out (Time Range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_transmit_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total Out (Time Range)"
    }
   ]
  },
  {
   "title": "Total Out (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_transmit_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total Out (Today)"
    }
   ]
  },
  {
   "title": "Total Out (This Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_transmit_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total Out (This Week)"
    }
   ]
  },
  {
   "title": "Total Out (This Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_transmit_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total Out (This Month)"
    }
   ]
  },
  {
   "title": "Total Out (This Year)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(darkstat_network_transmit_bytes_total{host=~\"$host\"}[1d]))",
     "legendFormat": "Total Out (This Year)"
    }
   ]
  },
  { "title": "Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sonos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*sonos.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*sonos.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Echo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*echo.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*echo.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Mobile Devices",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*android-*.*|.*ipad.*|.*fire.*|.*iphone.*|.*ipad.*|.*applewatch.*|.*kindle.*|.*nexus.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*android-*.*|.*fire.*|.*iphone.*|.*ipad.*|.*applewatch.*|.*kindle.*|.*nexus.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Client / Printer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*imac.*|.*mbp.*|.*kiosk.*|.*printer.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*imac.*|.*mbp.*|.*kiosk.*|.*printer.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Home Assistant",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*hass.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_network_transmit_bytes_total{host=~\".*hass.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Games / Media",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*tv-.*|.*xbox.*|.*tv-.*|.*shield.*|.*plex.*|.*switch.*|.*oculus.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*tv-.*|.*xbox.*|.*tv-.*|.*shield.*|.*plex.*|.*switch.*|.*oculus.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*app0.*|.*dns.*|.*attic.*|.*build.*|.*db01.*|.*demo.*|.*docker.*|.*grafana.*|.*graphite.*|.*influxdb.*|.*kub.*|.*lb0.*|.*log.*|.*probe.*|.*prom.*||.*sync.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*app0.*|.*dns.*|.*attic.*|.*build.*|.*db01.*|.*demo.*|.*docker.*|.*grafana.*|.*graphite.*|.*influxdb.*|.*kub.*|.*lb0.*|.*log.*|.*probe.*|.*prom.*||.*sync.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Render Farm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*render.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*render.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "IoT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*tesla.*|.*scale.*|.*rachio.*|.*bond.*|.*sense.*|.*myq.*|.*fingbox.*|.*apc.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_transmit_bytes_total{host=~\".*tesla.*|.*scale.*|.*rachio.*|.*bond.*|.*sense.*|.*myq.*|.*fingbox.*|.*apc.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Unifi",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(darkstat_network_receive_bytes_total{host=~\".*sw-.*|.*unifi.*\"}[$__rate_interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "-rate(darkstat_network_receive_bytes_total{host=~\".*sw-.*|.*unifi.*\"}[$__rate_interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Totals (Individual)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total In",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(darkstat_network_receive_bytes_total{host=~\"$host\"}[1d])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Total Out",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(darkstat_network_transmit_bytes_total{host=~\"$host\"}[1d])",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter Scrape",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "script_duration_seconds{script=\"darkstat\"}"
      }
     ]
    }
   ]
  }
 ]
}