{
 "title": "Darkstat",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(darkstat_net_in, host)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\"$host\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\"$host\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  { "title": "Total In (By Host Selection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total In (Time Range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_in{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total In (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_in{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total In (This Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_in{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total In (This Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_in{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total In (This Year)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_in{host=~\"$host\"}"
    }
   ]
  },
  { "title": "Total Out (By Host Selection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Out (Time Range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_out{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total Out (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_out{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total Out (This Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_out{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total Out (This Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_out{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total Out (This Year)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkstat_net_out{host=~\"$host\"}"
    }
   ]
  },
  { "title": "Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sonos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*sonos.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*sonos.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Echo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*echo.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*echo.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Mobile Devices",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*ipad.*|.*fire.*|.*iphone.*|.*ipad.*|.*applewatch.*|.*kindle.*|.*nexus.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*ipad.*|.*fire.*|.*iphone.*|.*ipad.*|.*applewatch.*|.*kindle.*|.*nexus.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Client / Printer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*imac.*|.*mbp.*|.*kiosk.*|.*printer.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*imac.*|.*mbp.*|.*kiosk.*|.*printer.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "SmartThings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*st-.*|.*smartthings.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*st-.*|.*smartthings.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Games / Media",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*tv-.*|.*xbox.*|.*tv-.*|.*shield.*|.*plex.*|.*switch.*|.*oculus.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*tv-.*|.*xbox.*|.*tv-.*|.*shield.*|.*plex.*|.*switch.*|.*oculus.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*app0.*|.*dns.*|.*attic.*|.*build.*|.*db01.*|.*demo.*|.*docker.*|.*grafana.*|.*graphite.*|.*influxdb.*|.*kub.*|.*lb0.*|.*log.*|.*probe.*|.*prom.*||.*sync.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*app0.*|.*dns.*|.*attic.*|.*build.*|.*db01.*|.*demo.*|.*docker.*|.*grafana.*|.*graphite.*|.*influxdb.*|.*kub.*|.*lb0.*|.*log.*|.*probe.*|.*prom.*||.*sync.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Render Farm",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*render.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*render.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "IoT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*tesla.*|.*scale.*|.*rachio.*|.*bond.*|.*sense.*|.*myq.*|.*fingbox.*|.*apc.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_out{host=~\".*tesla.*|.*scale.*|.*rachio.*|.*bond.*|.*sense.*|.*myq.*|.*fingbox.*|.*apc.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Unifi",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(darkstat_net_in{host=~\".*sw-.*|.*unifi.*\"}[$__interval])",
     "legendFormat": "In: {{host}}"
    },
    {
     "expr": "rate(darkstat_net_in{host=~\".*sw-.*|.*unifi.*\"}[$__interval])",
     "legendFormat": "Out: {{host}}"
    }
   ]
  },
  {
   "title": "Totals (Individual)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Out",
     "type": "stat",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "darkstat_net_out{host=~\"$host\"}",
       "legendFormat": "Out: {{host}}"
      }
     ]
    },
    {
     "title": "Total In",
     "type": "stat",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "darkstat_net_in{host=~\"$host\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter Scrape",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "script_duration_seconds{script=\"darkstat\"}"
      }
     ]
    }
   ]
  }
 ]
}