services:
  darkstat-exporter:
    command: -config.file /opt/config.yaml
    container_name: darkstat-exporter
    image: docker01.tylephony.com:5000/lux4rd0/darkstat-exporter:latest
    logging:
      driver: loki
      options:
        loki-url: http://log01.tylephony.com:3100/loki/api/v1/push
    ports:
    - published: 9469
      target: 9469
    restart: always
    volumes:
    - /mnt/docker/darkstat-exporter:/opt:ro
version: '3.3'
